name: Skyblock
version: '${project.version}'
main: xyz.lotho.me.skyblock.Skyblock
api-version: 1.18
depend: [ WorldEdit ]
authors: [ markxhewson, Lotho, Engineous ]
description: A skyblock plugin for Minecraft.
